services:
  mongo:
    image: mongo:8.0
    container_name: mongo_container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # ---------- Development backend ----------
  backend-dev:
    build:
      context: ./backend
      target: dev
    container_name: backend_dev_container
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "3401:3400"
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  # ---------- Production backend ----------
  backend-prod:
    build:
      context: ./backend
      target: prod
    container_name: backend_prod_container
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "3400:3400"
    depends_on:
      - mongo
    command: npm start
  # ---------- Alias backend (defaults to dev) ----------
  backend:
    extends:
      service: backend-dev

volumes:
  mongo-data:
